// Import the createSlice function from Redux Toolkit
import { createSlice } from "@reduxjs/toolkit";

// Define the initial state for the authentication slice
const initialState = {
  isAuthenticated: false,
  user: null,
};

// Create the authentication slice using createSlice
const authSlice = createSlice({
  name: "auth",
  initialState,
  reducers: {
    // Reducer function for handling the login action
    login: (state, action) => {
      state.isAuthenticated = true;
      state.user = action.payload;
    },
    // Reducer function for handling the logout action
    logout: (state) => {
      state.isAuthenticated = false;
      state.user = null;
    },
  },
});

// Export the login and logout actions
export const { login, logout } = authSlice.actions;

// Selector function to select the authentication state from the Redux store
export const selectAuth = (state) => state.auth;

// Export the reducer function generated by createSlice
export default authSlice.reducer;
